---
application:
  name: "sseserver"
  project: "sse"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "test"
  version: "8.0"
routers:
- name: "main-sseserver"
  routes:
  - application_name: "sseserver"
    paths:
    - "/*"
